/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { FetchCategoriesControllerHandleParams } from ".././models";

import { axiosInstance } from "../../axios";
import type { ErrorType } from "../../axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const fetchCategoriesControllerHandle = (
  params: FetchCategoriesControllerHandleParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    { url: `/categories`, method: "GET", params, signal },
    options,
  );
};

export const getFetchCategoriesControllerHandleQueryKey = (
  params?: FetchCategoriesControllerHandleParams,
) => {
  return [`/categories`, ...(params ? [params] : [])] as const;
};

export const getFetchCategoriesControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchCategoriesControllerHandleQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
  > = ({ signal }) =>
    fetchCategoriesControllerHandle(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FetchCategoriesControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
>;
export type FetchCategoriesControllerHandleQueryError = ErrorType<unknown>;

export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchCategoriesControllerHandleParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFetchCategoriesControllerHandleQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
