/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { FetchProblemsControllerHandleParams } from "../models";

import { axiosInstance } from "../../axios";
import type { ErrorType } from "../../axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const fetchProblemsControllerHandle = (
  params: FetchProblemsControllerHandleParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    { url: `/problems`, method: "GET", params, signal },
    options,
  );
};

export const getFetchProblemsControllerHandleQueryKey = (
  params?: FetchProblemsControllerHandleParams,
) => {
  return [`/problems`, ...(params ? [params] : [])] as const;
};

export const getFetchProblemsControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchProblemsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFetchProblemsControllerHandleQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchProblemsControllerHandle>>
  > = ({ signal }) =>
    fetchProblemsControllerHandle(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FetchProblemsControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchProblemsControllerHandle>>
>;
export type FetchProblemsControllerHandleQueryError = ErrorType<unknown>;

export function useFetchProblemsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchProblemsControllerHandleParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchProblemsControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchProblemsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchProblemsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchProblemsControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchProblemsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchProblemsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFetchProblemsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
  TError = ErrorType<unknown>,
>(
  params: FetchProblemsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchProblemsControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFetchProblemsControllerHandleQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
