/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChangeUserRoleControllerHandle200,
  ChangeUserRoleControllerHandleBody,
  FetchUsersControllerHandle200,
} from ".././models";

import { axiosInstance } from "../../axios";
import type { ErrorType, BodyType } from "../../axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Lista todos os usuários do sistema com filtros baseados no role do usuário autenticado. ADMIN pode ver todos os usuários, DIRECTOR e abaixo não veem usuários ADMIN.
 * @summary Listar usuários
 */
export const fetchUsersControllerHandle = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<FetchUsersControllerHandle200>(
    { url: `/users`, method: "GET", signal },
    options,
  );
};

export const getFetchUsersControllerHandleQueryKey = () => {
  return [`/users`] as const;
};

export const getFetchUsersControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
  TError = ErrorType<null | null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFetchUsersControllerHandleQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchUsersControllerHandle>>
  > = ({ signal }) => fetchUsersControllerHandle(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FetchUsersControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchUsersControllerHandle>>
>;
export type FetchUsersControllerHandleQueryError = ErrorType<null | null>;

export function useFetchUsersControllerHandle<
  TData = Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchUsersControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchUsersControllerHandle<
  TData = Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchUsersControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchUsersControllerHandle<
  TData = Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar usuários
 */

export function useFetchUsersControllerHandle<
  TData = Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchUsersControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFetchUsersControllerHandleQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Altera o role de um usuário. ADMIN pode alterar qualquer role, DIRECTOR pode alterar apenas para roles de nível igual ou inferior.
 * @summary Alterar role do usuário
 */
export const changeUserRoleControllerHandle = (
  id: string,
  changeUserRoleControllerHandleBody: BodyType<ChangeUserRoleControllerHandleBody>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ChangeUserRoleControllerHandle200>(
    {
      url: `/users/${id}/role`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: changeUserRoleControllerHandleBody,
    },
    options,
  );
};

export const getChangeUserRoleControllerHandleMutationOptions = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeUserRoleControllerHandle>>,
    TError,
    { id: string; data: BodyType<ChangeUserRoleControllerHandleBody> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeUserRoleControllerHandle>>,
  TError,
  { id: string; data: BodyType<ChangeUserRoleControllerHandleBody> },
  TContext
> => {
  const mutationKey = ["changeUserRoleControllerHandle"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeUserRoleControllerHandle>>,
    { id: string; data: BodyType<ChangeUserRoleControllerHandleBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return changeUserRoleControllerHandle(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangeUserRoleControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof changeUserRoleControllerHandle>>
>;
export type ChangeUserRoleControllerHandleMutationBody =
  BodyType<ChangeUserRoleControllerHandleBody>;
export type ChangeUserRoleControllerHandleMutationError = ErrorType<
  null | null | null | null
>;

/**
 * @summary Alterar role do usuário
 */
export const useChangeUserRoleControllerHandle = <
  TError = ErrorType<null | null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeUserRoleControllerHandle>>,
      TError,
      { id: string; data: BodyType<ChangeUserRoleControllerHandleBody> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof changeUserRoleControllerHandle>>,
  TError,
  { id: string; data: BodyType<ChangeUserRoleControllerHandleBody> },
  TContext
> => {
  const mutationOptions =
    getChangeUserRoleControllerHandleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
