/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateLocationRequest,
  FetchLocationsControllerHandle200,
  FetchLocationsControllerHandleParams,
} from ".././models";

import { axiosInstance } from "../../axios";
import type { ErrorType, BodyType } from "../../axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Cria uma nova localização no sistema (requer role MANAGER+)
 * @summary Criar localização
 */
export const createLocationControllerHandle = (
  createLocationRequest: BodyType<CreateLocationRequest>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    {
      url: `/locations`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createLocationRequest,
      signal,
    },
    options,
  );
};

export const getCreateLocationControllerHandleMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLocationControllerHandle>>,
    TError,
    { data: BodyType<CreateLocationRequest> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLocationControllerHandle>>,
  TError,
  { data: BodyType<CreateLocationRequest> },
  TContext
> => {
  const mutationKey = ["createLocationControllerHandle"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLocationControllerHandle>>,
    { data: BodyType<CreateLocationRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createLocationControllerHandle(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLocationControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLocationControllerHandle>>
>;
export type CreateLocationControllerHandleMutationBody =
  BodyType<CreateLocationRequest>;
export type CreateLocationControllerHandleMutationError = ErrorType<
  null | null | null
>;

/**
 * @summary Criar localização
 */
export const useCreateLocationControllerHandle = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLocationControllerHandle>>,
      TError,
      { data: BodyType<CreateLocationRequest> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLocationControllerHandle>>,
  TError,
  { data: BodyType<CreateLocationRequest> },
  TContext
> => {
  const mutationOptions =
    getCreateLocationControllerHandleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retorna uma lista paginada de localizações disponíveis no sistema
 * @summary Buscar localizações
 */
export const fetchLocationsControllerHandle = (
  params?: FetchLocationsControllerHandleParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<FetchLocationsControllerHandle200>(
    { url: `/locations`, method: "GET", params, signal },
    options,
  );
};

export const getFetchLocationsControllerHandleQueryKey = (
  params?: FetchLocationsControllerHandleParams,
) => {
  return [`/locations`, ...(params ? [params] : [])] as const;
};

export const getFetchLocationsControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchLocationsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFetchLocationsControllerHandleQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchLocationsControllerHandle>>
  > = ({ signal }) =>
    fetchLocationsControllerHandle(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FetchLocationsControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchLocationsControllerHandle>>
>;
export type FetchLocationsControllerHandleQueryError = ErrorType<null>;

export function useFetchLocationsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
  TError = ErrorType<null>,
>(
  params: undefined | FetchLocationsControllerHandleParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchLocationsControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchLocationsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchLocationsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchLocationsControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchLocationsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchLocationsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar localizações
 */

export function useFetchLocationsControllerHandle<
  TData = Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchLocationsControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchLocationsControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFetchLocationsControllerHandleQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
