const palette = {
  white: '#FFFFFF',
  greenishWhite: '#FCFDFD',
  darkGray: '#121214',
  gray: '#383D3B',
  lightGray: '#7C7C8A',
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E9ECEF',
  gray250: '#DEE2E6',
  gray300: '#D1D5DB',
  gray400: '#9CA3AF',
  gray500: '#6B7280',
  gray600: '#6C757D',
  gray700: '#374151',
  gray750: '#495057',
  gray800: '#44403C',
  gray850: '#2F2F2F',
  gray875: '#1F2937',
  gray900: '#212529',
  grayBlue100: '#E2E8F0',
  grayBorder: '#E5E5E5',
  grayDashed: '#ADB5BD',
  graySurface: '#F8F9FA',

  green: '#00875F',
  greenAccent: '#01EFA7',
  lightGreen: '#039855',
  lightGreen12Bg: '#0398551F',
  greenHover: '#00A66F',
  greenPressed: '#065F46',
  greenBorder: '#4A9960',
  greenStrong: '#059669',
  greenStrongHover: '#047857',
  greenSurface: '#F0FDF4',
  greenSurfaceHover: '#ECFDF5',
  greenDeep: '#166534',
  greenSoftBorder: '#BBF7D0',
  greenMuted: '#2D5A3D',

  darkBlue: '#083A98',
  darkBlue12Bg: '#083A981F',
  blue: '#0052EA',
  blue12Bg: '#0052EA1F',
  blueSoft: '#DBEAFE',
  blueStrong: '#1E40AF',
  blueInfoSurface: '#E3F2FD',
  blueInfoText: '#1976D2',

  orange: '#FF6F00',
  orange12Bg: '#FF6F001F',
  orangeSoft: '#FEF3C7',
  orangeStrong: '#D97706',
  orangeText: '#92400E',

  yellow: '#FCA004',
  yellow12Bg: '#FCA0041F',

  red: '#9A0E03',
  red12Bg: '#9A0E031F',
  redSoftBorder: '#9A0E0333',
  redStrong: '#DC3545',
  redLightBorder: '#F8D7DA',
}

export const colors = {
  ...palette,

  surfaceBase: palette.white,
  surfaceAlt: palette.greenishWhite,
  surfaceSubtle: palette.gray50,
  surfaceMuted: palette.gray100,
  surfaceNeutral: palette.graySurface,
  surfaceInfo: palette.blueSoft,
  surfaceInfoMuted: palette.blueInfoSurface,
  surfaceWarning: palette.orangeSoft,
  surfaceSuccess: palette.greenSurface,
  surfaceSuccessHover: palette.greenSurfaceHover,
  surfaceDanger: palette.red12Bg,

  borderSoft: palette.gray200,
  borderSubtle: palette.gray250,
  borderDefault: palette.gray300,
  borderLight: palette.grayBlue100,
  borderMuted: palette.grayBorder,
  borderDashed: palette.grayDashed,
  borderSuccess: palette.greenBorder,
  borderSuccessSoft: palette.greenSoftBorder,
  borderDangerSoft: palette.redSoftBorder,
  borderDangerLight: palette.redLightBorder,

  textPrimary: palette.gray875,
  textBody: palette.gray900,
  textSecondary: palette.gray600,
  textMuted: palette.gray500,
  textDisabled: palette.gray400,
  textNeutral: palette.gray700,
  textTertiary: palette.gray750,
  textHeadline: palette.gray800,
  textStrong: palette.gray850,
  textSubtle: palette.lightGray,
  textInfo: palette.blueStrong,
  textInfoMuted: palette.blueInfoText,
  textWarning: palette.orangeText,
  textWarningAccent: palette.orangeStrong,
  textSuccess: palette.greenDeep,
  textDanger: palette.red,
  textDangerStrong: palette.redStrong,

  brandPrimary: palette.green,
  brandPrimaryHover: palette.greenHover,
  brandPrimaryPressed: palette.greenPressed,
  brandAccent: palette.greenAccent,
  brandMuted: palette.greenMuted,

  feedbackSuccess: palette.greenStrong,
  feedbackSuccessHover: palette.greenStrongHover,
  feedbackInfo: palette.blue,
  feedbackWarning: palette.orange,
  feedbackDanger: palette.red,
}
