/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export interface CreateProblemRequest {
  /** Título do problema */
  title: string;
  /** Descrição detalhada do problema */
  description: string;
  /** ID da categoria do problema */
  categoryId?: string;
  /** ID da localização onde ocorreu o problema */
  locationId: string;
  /** IDs dos anexos (retornados pelo upload) */
  attachmentIds?: string[];
}
