/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export interface EditCategoryRequest {
  /** Nome da categoria */
  name?: string;
  /** Descrição da categoria */
  description?: string;
  /** Status ativo/inativo da categoria */
  isActive?: boolean;
}
