/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import type { LocationResponse } from "./locationResponse";

export type FetchLocationsControllerHandle200 = {
  locations?: LocationResponse[];
};
