/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import type { FetchUsersControllerHandle200UsersItem } from "./fetchUsersControllerHandle200UsersItem";

export type FetchUsersControllerHandle200 = {
  users?: FetchUsersControllerHandle200UsersItem[];
};
