/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export type FetchProblemsControllerHandleParams = {
/**
 * Número da página (começa em 1)
 */
page?: number;
/**
 * Incluir problemas deletados (na lixeira)
 */
includeDeleted?: boolean;
/**
 * Termo de busca para filtrar problemas por título ou descrição
 */
query?: string;
};
