/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export type FetchUsersControllerHandleParams = {
/**
 * Termo de busca para filtrar usuários por nome ou email
 */
query?: string;
/**
 * Filtrar usuários por status (true para ativos, false para inativos)
 */
isActive?: boolean;
};
