/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import type { FetchUsersControllerHandle200UsersItemRole } from './fetchUsersControllerHandle200UsersItemRole';

export type FetchUsersControllerHandle200UsersItem = {
  id?: string;
  name?: string;
  email?: string;
  position?: string;
  role?: FetchUsersControllerHandle200UsersItemRole;
  /** Indica se o usuário está ativo no sistema */
  isActive?: boolean;
};
