/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo de manutenção
 */
export type ManageProblemRequestMaintenanceType = typeof ManageProblemRequestMaintenanceType[keyof typeof ManageProblemRequestMaintenanceType];


export const ManageProblemRequestMaintenanceType = {
  PREVENTIVE: 'PREVENTIVE',
  CORRECTIVE: 'CORRECTIVE',
} as const;
