/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status do problema
 */
export type ProblemResponseStatus = typeof ProblemResponseStatus[keyof typeof ProblemResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProblemResponseStatus = {
  TO_ANALYSIS: 'TO_ANALYSIS',
  IN_ANALYSIS: 'IN_ANALYSIS',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
} as const;
