/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import type { ProblemHistoryChangeResponse } from './problemHistoryChangeResponse';
import type { ProblemHistoryEntryResponseAction } from './problemHistoryEntryResponseAction';
import type { ProblemHistoryEntryResponseNote } from './problemHistoryEntryResponseNote';

export interface ProblemHistoryEntryResponse {
  /** ID do registro de histórico */
  id: string;
  /** Ação realizada no histórico do problema */
  action: ProblemHistoryEntryResponseAction;
  /** Nome do usuário que realizou a ação */
  userName: string;
  /**
   * Observação adicionada ao histórico
   * @nullable
   */
  note?: ProblemHistoryEntryResponseNote;
  /**
   * Lista de mudanças agrupadas no registro de histórico
   * @nullable
   */
  changes?: ProblemHistoryChangeResponse[] | null;
  /** Data de criação do registro de histórico */
  createdAt: string;
}
