/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import type { ProblemHistoryEntryResponseAction } from './problemHistoryEntryResponseAction';
import type { ProblemHistoryEntryResponseNewValue } from './problemHistoryEntryResponseNewValue';
import type { ProblemHistoryEntryResponseNote } from './problemHistoryEntryResponseNote';
import type { ProblemHistoryEntryResponseOldValue } from './problemHistoryEntryResponseOldValue';

export interface ProblemHistoryEntryResponse {
  /** ID do registro de histórico */
  id: string;
  /** Ação realizada no histórico do problema */
  action: ProblemHistoryEntryResponseAction;
  /** Nome do usuário que realizou a ação */
  userName: string;
  /**
   * Valor antigo da alteração
   * @nullable
   */
  oldValue?: ProblemHistoryEntryResponseOldValue;
  /**
   * Novo valor da alteração
   * @nullable
   */
  newValue?: ProblemHistoryEntryResponseNewValue;
  /**
   * Observação adicionada ao histórico
   * @nullable
   */
  note?: ProblemHistoryEntryResponseNote;
  /** Data de criação do registro de histórico */
  createdAt: string;
}
