/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo de manutenção
 * @nullable
 */
export type ProblemResponseMaintenanceType = typeof ProblemResponseMaintenanceType[keyof typeof ProblemResponseMaintenanceType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProblemResponseMaintenanceType = {
  PREVENTIVE: 'PREVENTIVE',
  CORRECTIVE: 'CORRECTIVE',
} as const;
