/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

/**
 * Observação adicionada ao histórico
 * @nullable
 */
export type ProblemHistoryEntryResponseNote = { [key: string]: unknown } | null;
