/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export type SyncGoogleSheetControllerHandleBody = {
  /** ID da planilha (da URL: docs.google.com/spreadsheets/d/{ID}/edit) */
  spreadsheetId: string;
  /** Nome da aba (padrão: Formulário 1) */
  sheetName?: string;
};
