/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseRole } from "./userResponseRole";

export interface UserResponse {
  /** ID do usuário */
  id: string;
  /** Nome do usuário */
  name: string;
  /** Email do usuário */
  email: string;
  /** Cargo/posição do usuário */
  position: string;
  /** Role do usuário */
  role: UserResponseRole;
}
