/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateCategoryRequest,
  FetchCategoriesControllerHandle200,
  FetchCategoriesControllerHandleParams,
} from ".././models";

import { axiosInstance } from "../../axios";
import type { ErrorType, BodyType } from "../../axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna uma lista paginada de categorias de problemas disponíveis no sistema
 * @summary Buscar categorias
 */
export const fetchCategoriesControllerHandle = (
  params?: FetchCategoriesControllerHandleParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<FetchCategoriesControllerHandle200>(
    { url: `/categories`, method: "GET", params, signal },
    options,
  );
};

export const getFetchCategoriesControllerHandleQueryKey = (
  params?: FetchCategoriesControllerHandleParams,
) => {
  return [`/categories`, ...(params ? [params] : [])] as const;
};

export const getFetchCategoriesControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getFetchCategoriesControllerHandleQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
  > = ({ signal }) =>
    fetchCategoriesControllerHandle(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FetchCategoriesControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
>;
export type FetchCategoriesControllerHandleQueryError = ErrorType<null>;

export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<null>,
>(
  params: undefined | FetchCategoriesControllerHandleParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar categorias
 */

export function useFetchCategoriesControllerHandle<
  TData = Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
  TError = ErrorType<null>,
>(
  params?: FetchCategoriesControllerHandleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof fetchCategoriesControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFetchCategoriesControllerHandleQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Cria uma nova categoria de problema (requer role MANAGER+)
 * @summary Criar categoria
 */
export const createCategoryControllerHandle = (
  createCategoryRequest: BodyType<CreateCategoryRequest>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    {
      url: `/categories`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCategoryRequest,
      signal,
    },
    options,
  );
};

export const getCreateCategoryControllerHandleMutationOptions = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCategoryControllerHandle>>,
    TError,
    { data: BodyType<CreateCategoryRequest> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCategoryControllerHandle>>,
  TError,
  { data: BodyType<CreateCategoryRequest> },
  TContext
> => {
  const mutationKey = ["createCategoryControllerHandle"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCategoryControllerHandle>>,
    { data: BodyType<CreateCategoryRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createCategoryControllerHandle(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCategoryControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCategoryControllerHandle>>
>;
export type CreateCategoryControllerHandleMutationBody =
  BodyType<CreateCategoryRequest>;
export type CreateCategoryControllerHandleMutationError = ErrorType<
  null | null | null
>;

/**
 * @summary Criar categoria
 */
export const useCreateCategoryControllerHandle = <
  TError = ErrorType<null | null | null>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCategoryControllerHandle>>,
      TError,
      { data: BodyType<CreateCategoryRequest> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCategoryControllerHandle>>,
  TError,
  { data: BodyType<CreateCategoryRequest> },
  TContext
> => {
  const mutationOptions =
    getCreateCategoryControllerHandleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
