/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { UserResponse } from ".././models";

import { axiosInstance } from "../../axios";
import type { ErrorType } from "../../axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna as informações do perfil do usuário autenticado
 * @summary Obter perfil do usuário
 */
export const getUserProfileControllerHandle = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<UserResponse>(
    { url: `/profile`, method: "GET", signal },
    options,
  );
};

export const getGetUserProfileControllerHandleQueryKey = () => {
  return [`/profile`] as const;
};

export const getGetUserProfileControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
  TError = ErrorType<null | null>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserProfileControllerHandleQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserProfileControllerHandle>>
  > = ({ signal }) => getUserProfileControllerHandle(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserProfileControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserProfileControllerHandle>>
>;
export type GetUserProfileControllerHandleQueryError = ErrorType<null | null>;

export function useGetUserProfileControllerHandle<
  TData = Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserProfileControllerHandle<
  TData = Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileControllerHandle>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserProfileControllerHandle<
  TData = Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obter perfil do usuário
 */

export function useGetUserProfileControllerHandle<
  TData = Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
  TError = ErrorType<null | null>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProfileControllerHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserProfileControllerHandleQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
