/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export type ChangeUserPasswordControllerHandleBody = {
  /**
   * Senha atual do usuário
   * @minLength 6
   */
  oldPassword: string;
  /**
   * Nova senha do usuário
   * @minLength 6
   */
  newPassword: string;
};
