/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAccountRequest {
  /** Nome completo do usuário */
  name: string;
  /** Cargo/posição do usuário na instituição */
  position: string;
  /** Email institucional (domínios @ifal.edu.br ou @aluno.ifal.edu.br) */
  email: string;
  /**
   * Senha do usuário
   * @minLength 6
   */
  password: string;
}
