/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export interface CreateLocationRequest {
  /** Nome da localização */
  name: string;
  /** Descrição da localização */
  description: string;
  /** Código identificador da localização */
  code: string;
}
