/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export interface EditLocationRequest {
  /** Nome da localização */
  name?: string;
  /** Código identificador da localização */
  code?: string;
  /** Descrição da localização */
  description?: string;
  /** Status ativo/inativo da localização */
  isActive?: boolean;
}
