/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export interface EditProblemRequest {
  /** Novo título do problema */
  title: string;
  /** Nova descrição do problema */
  description: string;
}
