/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export type FetchUsersControllerHandle200UsersItemRole =
  (typeof FetchUsersControllerHandle200UsersItemRole)[keyof typeof FetchUsersControllerHandle200UsersItemRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FetchUsersControllerHandle200UsersItemRole = {
  REPORTER: "REPORTER",
  MANAGER: "MANAGER",
  DIRECTOR: "DIRECTOR",
  ADMIN: "ADMIN",
} as const;
