/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

export interface ProblemResponse {
  id: string;
  title: string;
  description: string;
  slug: string;
  categoryId: string;
  locationId: string;
  authorId: string;
  createdAt: string;
}
