/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */

/**
 * Role do usuário
 */
export type UserResponseRole = typeof UserResponseRole[keyof typeof UserResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRole = {
  REPORTER: 'REPORTER',
  MANAGER: 'MANAGER',
  DIRECTOR: 'DIRECTOR',
  ADMIN: 'ADMIN',
} as const;
