/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IFAL Arapiraca Backend API
 * API para gerenciamento de problemas de infraestrutura do IFAL Arapiraca
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import { axiosInstance } from "../../axios";
import type { ErrorType } from "../../axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const createLocationControllerHandle = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    { url: `/locations`, method: "POST", signal },
    options,
  );
};

export const getCreateLocationControllerHandleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLocationControllerHandle>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLocationControllerHandle>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["createLocationControllerHandle"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLocationControllerHandle>>,
    void
  > = () => {
    return createLocationControllerHandle(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLocationControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLocationControllerHandle>>
>;

export type CreateLocationControllerHandleMutationError = ErrorType<unknown>;

export const useCreateLocationControllerHandle = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLocationControllerHandle>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLocationControllerHandle>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getCreateLocationControllerHandleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
